/* Write your T-SQL query statement below */

SELECT P.PRODUCT_ID, P.PRODUCT_NAME 
FROM PRODUCT P JOIN 
(
    SELECT DISTINCT S1.PRODUCT_ID FROM SALES S1 
    WHERE NOT EXISTS
    (
        SELECT 1 FROM SALES S2
        WHERE (S2.SALE_DATE > '2019-03-31' OR S2.SALE_DATE < '2019-01-01') 
        AND S1.PRODUCT_ID = S2.PRODUCT_ID
    )
) AS S
ON P.PRODUCT_ID = S.PRODUCT_ID